[package]
name = "nix3docker"
version = "0.1.0"
authors = ["Benjamin Herr <ben@0x539.de>"]

[dependencies]
hyper = "0.12"
failure = "0.1"
structopt = "0.2"
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
sha2 = "0.7.1"
bytes = "0.4"
